old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOST)%'
            port: '%env(RABBITMQ_PORT)%'
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost: '%env(RABBITMQ_VHOST)%'

    consumers:
        connect_to_chat:
            connection: default
            queue_options:
                name: connect_to_chat
                arguments:
                    x-message-ttl: [ 'I', 1000 ]
                    x-expires: [ 'I', 60000 ]
            qos_options:
                prefetch_count: 10
            callback: App\Consumer\ConnectToChatConsumer

        save_db:
            connection: default
            queue_options:
                name: messages
                arguments:
                    x-dead-letter-exchange: [ 'S', dlx_save_db ]
            qos_options:
                prefetch_count: 10
            callback: App\Consumer\SaveDBConsumer

        dlx_save_db:
            connection: default
            exchange_options:
                name: dlx_save_db
                type: fanout
            queue_options:
                durable: false
                auto_delete: true
            callback: App\Consumer\DlxSaveDBConsumer
